kind: pipeline
type: exec
name: default

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: deploy
    environment:
      FLY_API_TOKEN:
        from_secret: FLY_API_TOKEN
    commands:
      - nix shell --command bash ./scripts/deploy.sh
