baseURL = "http://fcuny.net/"
languageCode = "en-us"
title = "Franck Cuny's Website"
publishDir = "docs"
enableGitInfo = true

[params]
  homeText = "A collection of notes"

[taxonomies]
  tag = "tags"

[permalinks]
  articles = "/:section/:slug/"
  tags = "/tags/:slug/"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "emacs"
    tabWidth = 4

[mediaTypes."application/atom"]
  suffixes = ["xml"]

[outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "feed"
  isPlainText = false

[outputs]
  home = [ "HTML", "Atom" ]
