baseURL = "http://fcuny.net/"
languageCode = "en-us"
title = "Franck Cuny's Website"
publishDir = "docs"
enableGitInfo = true
markup = "org"

[params]
  homeText = "A collection of notes"

[taxonomies]
  tag = "tags"

[permalinks]
  articles = "/:section/:slug/"
  tags = "/tags/:slug/"

[mediaTypes."application/atom"]
  suffixes = ["xml"]

[outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "feed"
  isPlainText = false

[outputs]
  home = [ "HTML", "Atom" ]
