baseURL = "https://fcuny.net/"
languageCode = "en-us"
title = "Franck's rambling"
publishDir = "docs"
enableGitInfo = true

[params]
  homeText = "A collection of notes"

[author]
  name = "Franck Cuny"
  email = "franck@fcuny.net"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:slug/"
  notes = "/notes/:slug/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
    identifier = "RSS"
    name = "RSS"
    title = "~/blog/feed"
    url = "/feed.xml"
    weight = 130

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "manni"
    tabWidth = 4

[mediaTypes."application/atom"]
  suffixes = ["xml"]

[outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "feed"
  isPlainText = false

[outputs]
  home = [ "HTML", "Atom" ]
