baseURL = "https://fcuny.net/"
languageCode = "en-us"
title = "Franck's rambling"
publishDir = "docs"
enableGitInfo = true

[params]
  homeText = "A collection of notes"

[author]
  name = "Franck Cuny"
  email = "franck@fcuny.net"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:slug/"
  notes = "/notes/:slug/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "fcuny.net"
    url = "/"
    weight = 100

  [[menu.main]]
    identifier = "articles"
    name = "blog"
    title = "articles"
    url = "/blog/"
    weight = 110

  [[menu.main]]
    identifier = "notes"
    name = "notes"
    title = "notes"
    url = "/notes/"
    weight = 120

  [[menu.main]]
    identifier = "RSS"
    name = "RSS"
    title = "RSS"
    url = "/feed.xml"
    weight = 130

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "emacs"
    tabWidth = 4

[mediaTypes."application/atom"]
  suffixes = ["xml"]

[outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "feed"
  isPlainText = false

[outputs]
  home = [ "HTML", "Atom" ]
