base_url = "https://fcuny.net/"

title = "@fcuny"
author = "Franck Cuny"
description = "random stuff about computers."

output_dir = "docs"

default_language = "en"

generate_feeds = false

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true
smart_punctuation = true

[extra]
license = { name = "CC BY-SA 4.0", href = "https://creativecommons.org/licenses/by-sa/4.0/" }
