baseURL = "https://fcuny.net/"
languageCode = "en-us"
title = "Franck's rambling"
publishDir = "docs"
enableGitInfo = false

[params]
  homeText = "A collection of posts"

[author]
  name = "Franck Cuny"
  email = "franck@fcuny.net"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:slug/"
  notes = "/notes/:slug/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    url = "/blog/"
    weight = 110

  [[menu.main]]
    identifier = "notes"
    name = "notes"
    title = "notes"
    url = "/notes/"
    weight = 120

  [[menu.main]]
    identifier = "code"
    name = "code"
    title = "code"
    url = "https://git.fcuny.net/fcuny/"
    weight = 130

  [[menu.main]]
    identifier = "feed"
    name = "feed"
    title = "feed"
    url = "/feed.xml"
    weight = 140

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "pygments"
    tabWidth = 4

[mediaTypes."application/atom"]
  suffixes = ["xml"]

[outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "feed"
  isPlainText = false

[outputs]
  home = [ "HTML", "Atom" ]
