base_url = "https://fcuny.net/"
default_language = "en"
title = "Franck's rambling"
output_dir = "docs"

author = "Franck Cuny"
description = "Franck's website, with articles about computers stuff."

[markdown]
highlight_code = true
highlight_theme = "idle"
render_emoji = true
smart_punctuation = true
