base_url = "https://fcuny.net/"

title = "@fcuny"
author = "Franck Cuny"
description = "Franck's website, with articles about computers stuff."

output_dir = "docs"

default_language = "en"

generate_feeds = true
feed_filenames = ["feed.xml"]

[markdown]
highlight_code = true
highlight_theme = "idle"
render_emoji = true
smart_punctuation = true

[extra]
license = { name = "CC BY-SA 4.0", href = "https://creativecommons.org/licenses/by-sa/4.0/" }
