baseURL = "https://fcuny.net/"
languageCode = "en-us"
title = "Franck's rambling"
publishDir = "docs"
enableGitInfo = false

[params]
homeText = "A collection of posts"

[params.author]
name = "Franck Cuny"
email = "franck@fcuny.net"

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = false
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = true
style = "pygments"
tabWidth = 4

[mediaTypes."application/atom"]
suffixes = ["xml"]

[outputFormats.Atom]
mediaType = "application/atom"
baseName = "feed"
isPlainText = false

[outputs]
home = ["HTML", "Atom"]
