name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix --log-format raw -L run .#deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
