name: ❄️ Flake Lock Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * 0"

# you need to grant permissions to create PR:
# https://github.com/DeterminateSystems/update-flake-lock/issues/75
jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "Update flake.lock"
          commit-msg: "chore: update flake"
          pr-assignees: fcuny
          pr-labels: |
            dependencies
            automated
