name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 7'

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@v14
        with:
          pr-title: "Update flake.lock"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Enable pull request automerge
        uses: peter-evans/enable-pull-request-automerge@v2
        if: ${{ steps.update-flake-lock.outputs.pull-request-number }}
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          merge-method: rebase
          pull-request-number: ${{ steps.update-flake-lock.outputs.pull-request-number }}

